theme: jekyll-theme-minimal
title: Kimi No Na Wa Webpage
description: Jimthereal first build completed webpage, which clone the official website of the movie "Your Name", as a path to learn HTML, CSS, and JavaScript.
